"""empty message

Revision ID: 489dec58ab33
Revises: 
Create Date: 2023-07-25 08:08:47.242255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489dec58ab33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volcano',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=30), nullable=True),
    sa.Column('last_eruption', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volcano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volcano_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volcano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volcano_name'))

    op.drop_table('volcano')
    # ### end Alembic commands ###
